'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const P=require('../book_mygpt_selection/web/projection.js');
function fixture(){
  const manifest={course_id:'course',book_id:'book',book_version_id:'book@v1',sections:[{id:'s'},{id:'support'}]};
  const record={id:'record',section_id:'s',title:'Synthetic fixture',parts:[{kind:'text',text:'raw',render_text:'display'},{kind:'math',latex:'x',render_latex:'x^2',display:true}]};
  const section={id:'s',records:[record],practice_groups:[]};
  const selected={course_id:'course',book_id:'book',book_version_id:'book@v1',section_id:'s',record_id:'record',layer:'source',layer_id:null,portion:'body',representation:'display'};
  return {manifest,record,section,selected};
}
for(const field of ['course_id','book_id','book_version_id','section_id','record_id'])test('identifier rejects final newline: '+field,()=>{const f=fixture();f.selected[field]+='\n';assert.throws(()=>P.selection(f.selected));});
for(const field of ['note','answers','prompt','provider'])test('private/request extension rejected: '+field,()=>{const f=fixture();f.selected[field]='private';assert.throws(()=>P.selection(f.selected));});
test('display, raw and parent identities are explicit',async()=>{const f=fixture();const d=await P.project(f.manifest,f.section,f.selected);const r=await P.project(f.manifest,f.section,{...f.selected,representation:'raw'});assert.equal(d.parts[0].text,'display');assert.equal(r.parts[0].text,'raw');assert.notEqual(await P.digest(d),await P.digest(r));assert.deepEqual(d.parent_sources,r.parent_sources);});
test('prime formula IDs are legitimate, paths are not',async()=>{const f=fixture();f.record.id=f.selected.record_id="eq-2.35'";assert.equal((await P.project(f.manifest,f.section,f.selected)).selection.record_id,"eq-2.35'");assert.throws(()=>P.selection({...f.selected,record_id:'../private'}));});
test('body excludes metadata and images',async()=>{const f=fixture();f.record.note='SECRET';f.record.parts.push({kind:'image',src:'private.png'});const p=await P.project(f.manifest,f.section,f.selected);assert.ok(!P.canonical(p).includes('SECRET'));assert.ok(!P.canonical(p).includes('private.png'));assert.ok(p.warnings.includes('NON_TEXT_PARTS_EXCLUDED'));});
test('Unicode code points agree with Python limits',()=>{assert.equal(P.parts([{kind:'text',text:'😀'.repeat(12000)}],'raw').parts.length,1);assert.throws(()=>P.parts([{kind:'text',text:'😀'.repeat(12001)}],'raw'));assert.throws(()=>P.parts([{kind:'text',text:'\ud800'}],'raw'));});
test('duplicate records and stale version fail closed',async()=>{const f=fixture();await assert.rejects(P.project(f.manifest,f.section,{...f.selected,book_version_id:'book@stale'}));f.section.records.push(structuredClone(f.record));await assert.rejects(P.project(f.manifest,f.section,f.selected));});
test('empty records cannot become an invented selection',async()=>{const f=fixture();f.record.parts=[];await assert.rejects(P.project(f.manifest,f.section,f.selected),/EMPTY_BODY/);});
test('completion is never silently source',async()=>{const f=fixture();f.record.source_completion={id:'completion',origin:'source_visual_transcription_not_generated_proof',parts:[{kind:'text',text:'source completion'}]};const s=await P.project(f.manifest,f.section,f.selected);assert.equal(s.parts[0].text,'display');const c=await P.project(f.manifest,f.section,{...f.selected,layer:'completion',layer_id:'completion'});assert.ok(c.origin.startsWith('SOURCE_COMPLETION'));});
test('correction requires exact source binding and remains unofficial',async()=>{const f=fixture();const c={id:'correction',course_id:'course',section_id:'s',record_id:'record',confidence:'HIGH',presentation:'prefer_corrected',status:'CHECKED_BY_ASSISTANT',evidence_status:'SCOPED_EVIDENCE_CHECKED',source_preserved:true,check_ids:['check'],original_title:f.record.title,original_parts:structuredClone(f.record.parts),corrected_parts:[{kind:'text',text:'AI correction'}]};f.record.corrections=[c];const q={...f.selected,layer:'correction',layer_id:'correction'};assert.ok((await P.project(f.manifest,f.section,q)).origin.includes('NOT_OFFICIAL'));c.original_parts[0].text='different';await assert.rejects(P.project(f.manifest,f.section,q));});
test('derived hint and solution stay separate with known supporting sections',async()=>{const f=fixture();const guide={source_record_ids:['record'],source_sections:['support'],textbook_official_solution:false,hint_parts:[{kind:'text',text:'hint'}],solution_parts:[{kind:'text',text:'solution'}]};f.section.practice_groups=[{id:'group',anchor_id:'record',record_ids:['record'],title:'Exercise',derived_guidance:guide}];const q={...f.selected,layer:'derived',layer_id:'group',portion:'hint'};assert.equal((await P.project(f.manifest,f.section,q)).parts[0].text,'hint');guide.source_sections=['unknown'];await assert.rejects(P.project(f.manifest,f.section,q));});
