/* Execute production renderers and actions in a Node VM. Not a browser layout test. */
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const ROOT=path.join(__dirname,'..'),ST=require('../web/study-engine.js'),EX=require('../web/exam-engine.js');
function setup(){
 const bid='functional_analysis_2e_jiang_sun',read=n=>JSON.parse(fs.readFileSync(path.join(ROOT,'web/data',bid+n+'.json'),'utf8'));
 const b=read('');b.study=read('.study');b.teaching=read('.teaching');b.study.solved=b.teaching.solved;b.byId=new Map(b.records.map(r=>[r.id,r]));b.studyById=new Map([...b.study.questions,...b.study.recalls,...b.study.lookups,...b.study.solved].map(g=>[g.id,g]));
 const s={personal:{schema:'book-personal-state-v1',settings:{},books:{},notes:{},bookmarks:{},cards:{}},currentBook:b,route:{mode:'practice',section:'ch01_s02'},currentSection:b.sections.find(s=>s.id==='ch01_s02')};const views={},inputs={};let n=0;
 const c={console,BookExam:EX,ST,state:s,Map,Date,Number,Math,Object,Array,JSON,Error,String,Set,Promise,esc:x=>String(x??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])),richText:x=>String(x),info:()=>({}),TYPES:{},safeSectionText:s=>s.title,
 loadBook:async()=>b,req:async()=>read('.learning'),studyView:(_,m)=>views[m]||(views[m]={}),getSession:(_,m)=>ST.personalBook(s.personal,bid).sessions[m],previewHTML:()=>'<p>preview</p>',learningHTML:()=>'<p>learning</p>',teachingUnitReview:()=>'',groupSource:g=>'<div>'+((g.source_question)||g.stem||g.record_ids.map(id=>b.byId.get(id)?.text).join(' '))+'</div>',originName:g=>g.origin,studyContextButton:()=>'<button>来源</button>',attemptHistory:()=>'<p>历史答案SECRET_OLD_ANSWER</p>',partsHTML:ps=>ps.map(p=>p.text||p.latex||'').join(''),
 studyAction:async el=>{c.baseActions.push(el.dataset.action)},bindStudyInput:()=>{c.inputCount++},inputCount:0,baseActions:[],flushStudy:async()=>{},mutate:async fn=>{const p=ST.clone(s.personal);fn(p);ST.validate(p);s.personal=p;},redrawStudy:async()=>{},routeTo:r=>{s.route=r},uid:()=>`new-${++n}`,toast:t=>{c.lastToast=t},$:sel=>inputs[sel]||null,document:{addEventListener:()=>{}},setInterval:fn=>{c.tick=fn},typeset:()=>{},window:{__bookTest:{}},boot:()=>{}};
 vm.createContext(c);
 const old=fs.readFileSync(path.join(ROOT,'web/study-ui.js'),'utf8');vm.runInContext(old.slice(old.indexOf('function sessionHTML('),old.indexOf('function learningHTML(')),c);
 vm.runInContext(fs.readFileSync(path.join(ROOT,'web/learning-ui.js'),'utf8'),c);
 return {c,b,s,views,inputs,bid,load:()=>c.loadBook(bid),run:code=>vm.runInContext(code,c)};
}
test('all source questions retain IDs and only 6 annotated originals enter ready pool',async()=>{const t=setup();await t.load();a.equal(t.c.examQuestions(t.b).filter(q=>q.origin==='textbook_question').length,6);a.equal(t.b.study.questions.length,110)});
test('pre-submission renderer hides answers, history, hints and source actions',async()=>{const t=setup();await t.load();let q=t.b.study.questions[0],ss=EX.create([q.id],'test',Date.now(),'chapter','ch01',20);const html=t.c.sessionHTML(t.b,t.s.currentSection,'practice',ss);a.ok(html.includes('交卷'));a.ok(!html.includes('SECRET_OLD_ANSWER'));a.ok(!html.includes('study-reveal'));a.ok(!html.includes('分步解答'));a.ok(!html.includes('回到来源'))});
test('submitted original renders method and locks the original draft',async()=>{const t=setup();await t.load();let q=t.b.study.questions[0],ss=EX.create([q.id],'test',Date.now(),'chapter','ch01',20);ss.drafts[q.id]='MY ORIGINAL';EX.submit(ss);ss.revealed[q.id]=true;const h=t.c.sessionHTML(t.b,t.s.currentSection,'practice',ss);a.ok(h.includes('方法总结'));a.ok(h.includes('textarea readonly'));a.ok(h.includes('MY ORIGINAL'));a.ok(h.includes('不是自动评分'));a.ok(h.includes('非原书标准答案'))});
test('UI rejects reveal and rating actions before submit',async()=>{const t=setup();await t.load();ST.personalBook(t.s.personal,t.bid).sessions.practice=EX.create([t.b.study.questions[0].id],'test',Date.now(),'chapter','ch01',20);await t.c.studyAction({dataset:{action:'study-reveal'}});await t.c.studyAction({dataset:{action:'study-rate',value:'2'}});a.equal(t.c.baseActions.length,0)});
test('submit action persists snapshots without fabricating marks',async()=>{const t=setup();await t.load();const ss=EX.create([t.b.study.questions[0].id],'test',Date.now(),'chapter','ch01',20);ss.drafts[ss.queue[0]]='proof';ST.personalBook(t.s.personal,t.bid).sessions.practice=ss;await t.c.studyAction({dataset:{action:'study-exam-submit'}});const saved=t.c.getSession(t.b,'practice');a.equal(saved.submitted_answers[ss.queue[0]],'proof');a.equal(Object.keys(t.s.personal.cards).length,0);a.equal(Object.keys(saved.results).length,0)});
test('post-submit programmatic input cannot change saved answer',async()=>{const t=setup();await t.load();const ss=EX.create([t.b.study.questions[0].id],'test',Date.now(),'chapter','ch01',20);EX.submit(ss);ST.personalBook(t.s.personal,t.bid).sessions.practice=ss;t.c.bindStudyInput({dataset:{studyDraft:'1'},value:'changed'});a.equal(t.c.inputCount,0)});
test('starting a chapter test archives previous attempts',async()=>{const t=setup();await t.load();const old=EX.create(['x'],'old',Date.now(),'quick','',20);old.drafts.x='keep';ST.personalBook(t.s.personal,t.bid).sessions.practice=old;t.inputs['#exam-chapter']={value:'ch01'};t.inputs['#exam-limit']={value:'5'};t.inputs['#exam-minutes']={value:'10'};await t.c.studyAction({dataset:{action:'study-exam-start',kind:'chapter'}});const st=ST.personalBook(t.s.personal,t.bid);a.equal(st.sessionHistory[0].drafts.x,'keep');a.equal(st.sessions.practice.queue.length,5);a.ok(st.sessions.practice.queue.every(id=>t.b.studyById.get(id).chapter_ids.includes('ch01')))});
test('deadline submits paused session when revisited',async()=>{const t=setup();await t.load();const ss=EX.create([t.b.study.questions[0].id],'test',0,'chapter','ch01',1);ss.status='paused';ST.personalBook(t.s.personal,t.bid).sessions.practice=ss;await t.c.studyAction({dataset:{action:'study-exam-resume'}});a.notEqual(t.c.getSession(t.b,'practice').submitted_at,null)});
test('tree exposes every directory without eagerly dumping all record bodies',async()=>{const t=setup();await t.load();const html=t.c.treeHTML(t.b);a.equal((html.match(/data-tree-section=/g)||[]).length,t.b.sections.length);a.ok(html.includes('精讲待补'));a.ok(!html.includes('data-tree-record='));const node=t.b.learning.sections.find(x=>x.record_count);a.ok(t.c.treeSectionHTML(t.b,node).includes('data-tree-record='))});
test('emphasis does not invent exam frequency',async()=>{const t=setup();await t.load();a.ok(t.c.emphasisHTML(t.b).includes('真题频次证据为 0'));a.ok(t.c.examHubHTML(t.b).includes('暂无真题频次统计'))});
test('failed sidecar loads leave source reader available',async()=>{const t=setup();t.c.req=async()=>{throw Error('network')};const b=await t.load();a.equal(b.learningError,'network');a.equal(b.study.questions.length,110);a.ok(t.c.treeHTML(b).includes('读取失败'))});
